version: '3.8'

services:
  db:
    container_name: postgres_database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clothes
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - /DataBase:/var/lib/postgresql/data
    restart: always

  bot:
    build: tgbot/
    restart: always
    expose:
      - "5432"